LOADLIBES=-pthread #-lrt
CXXFLAGS=-std=c++11

all: src/Sem_Ascensor/Inicializa src/Sem_Ascensor/Libera src/Sem_Ascensor/Pasajero src/Sem_Ascensor/Ascensor src/Sem_Ascensor/Finaliza src/Sem_Ascensor/Inicializa src/Sem_Ascensor/Libera src/Sem_Ascensor/Pasajero src/Sem_Ascensor/Ascensor src/Sem_Ascensor/Finaliza

clean:
	rm -f *~ src/Sem_Ascensor/Inicializa src/Sem_Ascensor/Libera src/Sem_Ascensor/Pasajero src/Sem_Ascensor/Ascensor src/Sem_Ascensor/Finaliza src/Sem_Ascensor/Inicializa src/Sem_Ascensor/Libera src/Sem_Ascensor/Pasajero src/Sem_Ascensor/Ascensor src/Sem_Ascensor/Finaliza
